spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
###security###
jwt:
  secret: swpu-uchain
  expiration: 1296000
###fabric-config###
fabric:
  channel-name: hmqchannel
  version: 1.0.0
  orderer-domain-name: example.com
  org-name: Org1
  org-msp-id: Org1MSP
  org-domain-name: org1.example.com

mybatis:
  mapper-locations: classpath:mappers/*.xml
